### ISSUE TITLE
No deinit() method

### ISSUE THREAD

**Issue by chrisgilldc** [adafruit/Adafruit_AW9523#2]
Good morning!

Trying to use HC-SR04 sensors via the AW9523 board. I'm trying to modify the hcsr04 library to accept the DigitalInOut objects from the AW9523 instance, but they don't have a deinit() method. This is counter to the notes in the AW9523 library, which say "this interface is exactly the same as the digitalio.DigitalInOut class". It's not, since at least one method is missing.

So either this library needs to be brought in line with the main digitalio.DigitalInOut class, or the notes should be updated to reflect that they're substantially the same but not 1:1 the same. I've love if it were the first, because then that makes this a drop-in replacement.

Thanks.

**Comment by caternuson** [comment]
This is an Arduino library. Your issue looks Circuit Python related? The Circuit Python library is here:
https://github.com/adafruit/Adafruit_CircuitPython_AW9523

**Comment by chrisgilldc** [comment]
It is, my mistake. Thanks!
