### ISSUE TITLE
### **AW9523B notworking**

### ISSUE THREAD

**Issue by luongvanchung93** [adafruit/Adafruit_AW9523#4]
I have encountered the problem that the library is not working with my circuit using ESP32-WROOM-32E.
i tried the blink example but it doesn't work with the IO pins i use. I don't know where I'm doing wrong, hope to get your help! thank you
![image](https://user-images.githubusercontent.com/45823969/171079156-399f1524-8118-46f1-a5da-d4f29ba2c483.png)

**Comment by luongvanchung93** [comment]
My code:
#include <Adafruit_AW9523.h>

Adafruit_AW9523 aw;

uint8_t LedPin = 5;  // 0 thru 15

void setup() {
  Serial.begin(115200);
  while (!Serial) delay(1);  // wait for serial port to open
  
  Serial.println("Adafruit AW9523 GPIO Expander test!");
  Wire.begin(32,33);
  if (! aw.begin(0x58)) {
    Serial.println("AW9523 not found? Check wiring!");
    while (1) delay(10);  // halt forever
  }

  Serial.println("AW9523 found!");
  aw.pinMode(LedPin, OUTPUT);
}


void loop() {
  aw.digitalWrite(LedPin, HIGH);
  Serial.println("HIGH");
  delay(1000);
  aw.digitalWrite(LedPin, LOW);
  Serial.println("LOW");
  delay(1000);
}

**Comment by ladyada** [comment]
the library definitely works with adafruit hardware. if you are designing your own hardware there's proably some mistake in the schematic. you can post on hardware forums like reddit for help with your design (we do not do design consultation!) 
thanks!

**Comment by luongvanchung93** [comment]
> 

thank you
