### ISSUE TITLE
aw9523 bits not properly working after recent update

### ISSUE THREAD

**Issue by klankschap** [adafruit/Adafruit_AW9523#8]
After updaating to the recent version, the AW9523 library did not work properly anymore.
e.g. the lower addresses wre not rechable.
Adjusting the code to this snippet, made it work again.
Please update the library with this fix.

void Adafruit_AW9523::analogWrite(uint8_t pin, uint8_t val) {
		uint8_t reg;
		// See Table 13. 256 step dimming control register
		if (pin <= 7) {
				reg = 0x24 + pin;
		} else if (pin <= 11) {
				reg = 0x20 + pin - 8;
		} else if (pin <= 15) {
				reg = 0x2C + pin - 12;
		} else {
				return;         // failed
		}
		Adafruit_I2CRegister ledCCreg = Adafruit_I2CRegister(i2c_dev, reg);
		ledCCreg.write(val);
}

**Comment by caternuson** [comment]
Thanks for spotting this. The logic was updated and release with 1.0.4:
https://github.com/adafruit/Adafruit_AW9523/releases/tag/1.0.4

**Comment by ladyada** [comment]
closed no response
